// src/components/Patchnotes.vue
<template>
  <div>
    <h1>Patchnotes</h1>
    <ul>
      <li v-for="note in patchnotes" :key="note.id">
        <h2>{{ note.version }}</h2>
        <h2>{{ note.description }}</h2>
        <p>{{ note.date }}</p>
        <ul>
          <li v-for="change in note.changes" :key="change.id">
            {{ change.description }}
          </li>
        </ul>
      </li>
    </ul>
  </div>
</template>


<script>

//get the json from the api/updates.json
import patchnotes from "../api/updates.json";

// read the json data and show it with the html
export default {
  name: "Patchnotes",
  data() {
    return {
      patchnotes: patchnotes
    };
  }
};
    
</script>

// src/components/Patchnotes.tsx

import React, { useState, useEffect } from 'react';

interface Patchnote {
  id: number;
  version: string;
  date: string;
  changes: string[];
}

const Patchnotes: React.FC = () => {
  const [patchnotes, setPatchnotes] = useState<Patchnote[]>([]);

  useEffect(() => {
    const fetchPatchnotes = async () => {
      const response = await fetch('https://api.example.com/patchnotes');
      const data = await response.json();
      setPatchnotes(data);
    };

    fetchPatchnotes();
  }, []);

  return (
    <div>
      <h1>Patchnotes</h1>
      <ul>
        {patchnotes.map((patchnote) => (
          <li key={patchnote.id}>
            <h2>{patchnote.version}</h2>
            <p>{patchnote.date}</p>
            <ul>
              {patchnote.changes.map((change, index) => (
                <li key={index}>{change}</li>
              ))}
            </ul>
          </li>
        ))}
      </ul>
    </div>
  );
};

export default Patchnotes;
